### PR TITLE
Fix rpm purls in the RPM examples

### PR DESCRIPTION
**Pull request by twaugh**

### CODE REVIEW

**Comment by twaugh** [comment]
@mprpic there's a problem though. None of these match the purls in eg the container image SBOMs. I think it was your intention to update those too, right?

And also... if we're including checksums I think we should instead be using the SHA256HEADER tag (ie digest of the RPM header) instead of the literal digest of the entire RPM artifact. As in:
```
$ rpm -q --qf "sha256:%{SHA256HEADER}\n" -p poppler-qt5-21.01.0-19.el9.x86_64.rpm 
sha256:d0a5c7eeb6bc03cb40b6319ea52ec52dfe359d7bd626c461036028e4cd7a15d0
```

Otherwise I don't know how it's even possible to produce an purl for an installed RPM -- the `.rpm` artifact is no longer around, but its header SHA256HEADER is recorded.

I'm starting to think it's a mistake to include a checksum in the purl at all. Why isn't `pkg:rpm/redhat/` sufficient?

**Comment by mprpic** [comment]
@twaugh Yea, I'm starting to like it less and less too. It'll be a constant source of confusion as to which exact checksum the value refers to if it's used within purls for component identification. I'll revert those changes in this PR and extend the docs on the namespace value to make it clear that it's the value that would differentiate potentially same-named artifacts in same-named repos.

**Comment by mprpic** [comment]
@twaugh f689d8db61bfab7dab5e34b2062660e668038afb reverts the change to add checksums and e0d8f37d560a05164c778f9946990b581f9595c2 changes the way we add them to look it up from the RPM headers instead of the `.rpm` file itself.

In the container manifests I have a comment that I left unresolved:

> # We don't have data on a checksum for binary RPMs included in images; should we?

I assume during the build in Konflux, we'll be able to query the RPM database to create these checksum values so they can be included in the SBOM, we just don't have it available here since we're constructing the example from data in Pyxis. Is that correct?

**Comment by mprpic** [comment]
I added a mock checksum value for all RPMs in a container.

**Pull request merged**
